services:

  aeronuk-flight-search:
    build: .
    container_name: aeronuk-flight-search
    ports:
      - "8000:8000"
    depends_on:
      - flight-search-db
    environment:
      DATABASE_URL: mysql://aeronuk:aeronuk@flight-search-db:3306/flight_search
    networks:
      - aeronuk-network

  flight-search-db:
    image: mysql:8
    container_name: aeronuk-flight-search-db
    environment:
      MYSQL_DATABASE: flight_search
      MYSQL_USER: aeronuk
      MYSQL_PASSWORD: aeronuk
      MYSQL_ROOT_PASSWORD: aeronuk
    volumes:
      - flight_search_mysql_data:/var/lib/mysql
    networks:
      - aeronuk-network

volumes:
  flight_search_mysql_data:

networks:
  aeronuk-network:
    name: aeronuk-network
    driver: bridge