services:

  aeronuk-flight-search:
    build:
      context: .
      target: frankenphp_dev
    container_name: aeronuk-flight-search
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/var
    environment:
      APP_ENV: dev
    depends_on:
      - flight-search-db
    networks:
      - aeronuk-network

  flight-search-db:
    image: mysql:8.4
    container_name: aeronuk-flight-search-db
    environment:
      MYSQL_DATABASE: flight_search
      MYSQL_USER: aeronuk
      MYSQL_PASSWORD: aeronuk
      MYSQL_ROOT_PASSWORD: aeronuk
    volumes:
      - flight_search_mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    networks:
      - aeronuk-network

volumes:
  flight_search_mysql_data:

networks:
  aeronuk-network:
    name: aeronuk-network
    driver: bridge
